### ISSUE TITLE
namespace example

### ISSUE THREAD

**Issue by roccomuso** [soyuka/IPCEE#4]
The namespace example on the README.md doesn't seem to work.

PS. Is it worth upgrading the `eventemitter2` library to the latest version `5.0.0` ?

Thanks

**Comment by soyuka** [comment]
Did you pass `{wildcard: true}`?

**Comment by soyuka** [comment]
Lol their changelog doesn't seem to bring breaking change to their major upgrades so yes it's safe/worth to update to `5.0.0` and I'd love a PR about that!

Note to myself: Maybee need too upgrade https://github.com/soyuka/TCPEE too! (library allows to do IPC-like with TCP instead so that processes aren't linked - failsafe)

**Comment by roccomuso** [comment]
The example:

- Master:

```javascript
const {fork} = require('child_process')
const IPCEE = require('ipcee')
const server = fork('./child.js')
const client = IPCEE(server, {wildcard: true})

client.once('started', () => {
  console.log('master: sending ping')
  client.send('ping:*')
})

client.once('*:pong', () => {
  console.log('got pong!')
})
```

- Child:

```javascript
const IPCEE = require('ipcee')
const ipc = IPCEE(process, {wildcard: true})

ipc.send('started')

// it doesn't even get the ping!
ipc.on('ping:me', () => {
  console.log('child: got ping')
  ipc.send('me:pong')
})
```
@soyuka cool I'm opening right now the PR

**Comment by roccomuso** [comment]
could you also "patch bump" and publish on npm? thanks

**Comment by soyuka** [comment]
yes gimme a minute just improving the tests and trying to get why  this isn't working for you

**Comment by soyuka** [comment]
I released as 2.0.0 because bumping eventemitter2 to `5.0.0` just in case ;)

**Comment by soyuka** [comment]
your issue is that you need `delimiter: ':'` in the options (fixed readme sorry bout that)

**Comment by roccomuso** [comment]
ok thanks! great
